# Generated by Django 3.2.9 on 2021-11-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catogery_name',
            new_name='category_name',
        ),
    ]
